### PR TITLE
fix nslookup panic

### LINKED ISSUE #178: Panic on RRSIG responses
Occasional RRSIG responses are not parsed correctly and cause panic.

As an example, a nslookup result like this
```
{[{300 A 1 IN 1 ns2.101domain.com 35.182.100.235} {300 A 1 IN 1 ns2.101domain.com 35.182.190.110} {RRSIG 46 IN 1 ns2.101domain.com.     300     IN      RRSIG   A 13 3 300 20200109121605 20200107101605 34505 101domain.com. h+oPZIi9GFvTepOeecO64MQrnvmID9xVhYaQdqRPmzyg/K2gSjZVVH7xT0wmTXht5Vt0eSw9MEPj1O/4inM5kw==}] [] [] udp 70.89.136.145:53 {true 0 false false true true false false 0}}
```

Will cause panic like this
```
panic: interface conversion: interface {} is struct { Type string "json:\"type\""; rrType uint16; Class string "json:\"class\""; rrClass uint16; Unparsed dns.RR "json:\"-\"" }, not miekg.Answer

goroutine 871 [running]:
github.com/zmap/zdns/modules/nslookup.(*Lookup).lookupIPs(0xc4211d7630, 0xc420f6fb40, 0x11, 0x1, 0x2, 0xc42150b4a0, 0x1, 0x2, 0x0, 0x0)
        /home/ec2-user/go/src/github.com/zmap/zdns/modules/nslookup/nslookup.go:59 +0x4ac
github.com/zmap/zdns/modules/nslookup.(*Lookup).DoNSLookup(0xc4211d7630, 0xc4214f6350, 0xa, 0xc4212b0000, 0x9500000000408c92, 0xc4212b3c5e, 0xc4200a2148, 0x151f56aafbefa001, 0x150000c4212b3c70, 0x0, ...)
        /home/ec2-user/go/src/github.com/zmap/zdns/modules/nslookup/nslookup.go:101 +0x7d5
github.com/zmap/zdns/modules/nslookup.(*Lookup).DoLookup(0xc4211d7630, 0xc4214f6350, 0xa, 0x0, 0xc4214f6350, 0xa, 0x0, 0x0, 0x6c1f85, 0x7, ...)
        /home/ec2-user/go/src/github.com/zmap/zdns/modules/nslookup/nslookup.go:128 +0x71
github.com/zmap/zdns.doLookup(0xc4200806c0, 0xc420096900, 0xc420070120, 0xc420070180, 0xc4200a0960, 0xc42008c2b0, 0x352, 0x29a7fc9a2c832f, 0x326)
        /home/ec2-user/go/src/github.com/zmap/zdns/lookup.go:114 +0x83a
created by github.com/zmap/zdns.DoLookups
        /home/ec2-user/go/src/github.com/zmap/zdns/lookup.go:176 +0x392
```

This might be related to https://github.com/zmap/zdns/pull/84

### PR DESCRIPTION
**Pull request by zakird**
This PR fixes #178 where *lookup modules incorrectly always assume an Answer object. It also fixes inconsistencies in how nslookup and mxlookup output data.

### CODE REVIEW

File: modules/alookup/alookup.go [hunk 1]
```diff
@@ -79,9 +78,8 @@ func (s *Lookup) doLookupProtocol(name string, nameServer string, dnsType uint16
 			}
 		}
 		for _, a := range miekgResult.(miekg.Result).Additional {
-			ans, ok := a.(miekg.Answer)
 			// filter only valid answers of requested type or CNAME (#163)
-			if ok {
+			if ans, ok := a.(miekg.Answer); ok {
```
Comment (dadrian) [inline modules/alookup/alookup.go:82]: Noting that this change doesn't do anything functionally

File: modules/nslookup/nslookup.go [hunk 2]
```diff
@@ -52,10 +52,12 @@ func (s *Lookup) lookupIPs(name string, dnsType uint16, nameServer string) ([]st
 	var addresses []string
 	res, trace, status, _ := s.DoTypedMiekgLookup(name, dnsType, nameServer)
 	if status == zdns.STATUS_NOERROR {
-		cast, _ := res.(miekg.Result)
-		for _, innerRes := range cast.Answers {
-			castInnerRes := innerRes.(miekg.Answer)
-			addresses = append(addresses, castInnerRes.Answer)
+		if cast, ok := res.(miekg.Result); ok {
```
Comment (dadrian) [inline modules/nslookup/nslookup.go:55]: Noting this is the only actual functionality change that relates to casting.

**Review by dadrian — APPROVED** [review]

File: modules/alookup/alookup.go (hunk 1 above)
Comment (zakird) [reply modules/alookup/alookup.go:82]: Thanks. Yeah, it was just consistent in that file.
