### PR TITLE
Remove MXLookup cache, add concept of caching lookups specific to a nameserver

### LINKED ISSUE #114: (A/NS/MX)Lookup should never interact with the cache, instead use miekg abstraction
Currently, cache operations at littered throughout the *lookups. This is not necessary, violates the abstractions, and makes trace not work properly. This should be replaced with cachedretryinglookup calls.

### PR DESCRIPTION
**Pull request by phillip-stephens**
Closes #114

## Description
- Modified the Cache to be keyed based off of DNS question (as it was before) + optional NameServer string
- Added a concept of caching lookups specific to name-servers
    - `ExternalLookups` will cache according to name-server. So `google.com @1.1.1.1` and `google.com @8.8.8.8` are not inter-changeable
    - `IterativeLookups` are not cached according to name-server. So `google.com @a.root-servers.net` is equivalent to `google.com @b.root-servers.net`
- When fetching from the cache, we'll use the nameserver and `resolver.Protocol` to populate the response protocol. The goal is for a cached answer to be identical to a non-cached one.
- Added unit tests around the cache and nameservers as keys

## Testing
Besides the unit tests, I ran the following test to be sure the cache was working for `MXLOOKUP`.

```
$ ./zdns MXLOOKUP gmail.com gmail.com --name-servers=1.1.1.1 --tcp-only --threads=1

{"name":"gmail.com","results":{"MXLOOKUP":{"data":{"exchanges":[{"class":"IN","ipv4_addresses":["64.233.186.27"],"name":"alt3.gmail-smtp-in.l.google.com","preference":30,"ttl":1703,"type":"MX"},{"class":"IN","ipv4_addresses":["209.85.202.27"],"name":"alt4.gmail-smtp-in.l.google.com","preference":40,"ttl":1703,"type":"MX"},{"class":"IN","ipv4_addresses":["108.177.12.27"],"name":"alt1.gmail-smtp-in.l.google.com","preference":10,"ttl":1703,"type":"MX"},{"class":"IN","ipv4_addresses":["172.253.62.27"],"name":"alt2.gmail-smtp-in.l.google.com","preference":20,"ttl":1703,"type":"MX"},{"class":"IN","ipv4_addresses":["142.251.182.26"],"name":"gmail-smtp-in.l.google.com","preference":5,"ttl":1703,"type":"MX"}]},"duration":0.133946875,"status":"NOERROR","timestamp":"2024-09-18T12:05:16-04:00"}}}
{"name":"gmail.com","results":{"MXLOOKUP":{"data":{"exchanges":[{"class":"IN","ipv4_addresses":["64.233.186.27"],"name":"alt3.gmail-smtp-in.l.google.com","preference":30,"ttl":1703,"type":"MX"},{"class":"IN","ipv4_addresses":["209.85.202.27"],"name":"alt4.gmail-smtp-in.l.google.com","preference":40,"ttl":1703,"type":"MX"},{"class":"IN","ipv4_addresses":["108.177.12.27"],"name":"alt1.gmail-smtp-in.l.google.com","preference":10,"ttl":1703,"type":"MX"},{"class":"IN","ipv4_addresses":["172.253.62.27"],"name":"alt2.gmail-smtp-in.l.google.com","preference":20,"ttl":1703,"type":"MX"},{"class":"IN","ipv4_addresses":["142.251.182.26"],"name":"gmail-smtp-in.l.google.com","preference":5,"ttl":1703,"type":"MX"}]},"duration":0.015629833,"status":"NOERROR","timestamp":"2024-09-18T12:05:16-04:00"}}}
```

You can see the 2nd duration is an order of magnitude less than the first. Wireshark confirms we're only repeating the `MX` query and not the subsequent `A` lookups

image

### Other Tests

To check reliability, I ran ZDNS over `google.com` + top_1k_domains + `google.com` to be sure we used the cached entry for `google` and it was correct.

```
$ grep "name\":\"google.com" out
{"name":"google.com","results":{"A":{"data":{"additionals":[{"flags":"","type":"EDNS0","udpsize":1232,"version":0}],"answers":[{"answer":"142.250.72.206","class":"IN","name":"google.com","ttl":155,"type":"A"}],"protocol":"udp","resolver":"1.1.1.1:53"},"duration":0.003749184,"status":"NOERROR","timestamp":"2024-09-18T16:08:52Z"}}}
{"name":"google.com","results":{"A":{"data":{"answers":[{"answer":"142.250.72.206","class":"IN","name":"google.com","ttl":155,"type":"A"}],"protocol":"udp","resolver":"1.1.1.1:53"},"duration":0.0000227,"status":"NOERROR","timestamp":"2024-09-18T16:08:53Z"}}}
```
The `Additional` wasn't retrieved from the cache, but this seems fine since it isn't retrieved using `dig` either.
```
$ dig -t A google.com         

; <<>> DiG 9.10.6 <<>> -t A google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56638
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             139     IN      A       142.250.190.78


```

### CODE REVIEW

File: src/zdns/lookup.go [hunk 1]
```diff
@@ -391,13 +391,19 @@ func (r *Resolver) iterativeLookup(ctx context.Context, q Question, nameServer *
 	}
 }
 
-func (r *Resolver) cachedRetryingLookup(ctx context.Context, q Question, nameServer *NameServer, layer string, depth int) (SingleQueryResult, IsCached, Status, int, error) {
+func (r *Resolver) cachedRetryingLookup(ctx context.Context, q Question, nameServer *NameServer, layer string, depth int, requestIteration, cacheBasedOnNameServer, cacheNonAuthoritative bool) (SingleQueryResult, IsCached, Status, int, error) {
```
Comment (phillip-stephens) [inline src/zdns/lookup.go:401]: add a comment explaining the new bools

**Review by zakird — APPROVED** [review]
